### ISSUE TITLE
Maven Java example does not work

### ISSUE THREAD

**Issue by galderz** [apache/incubator-openwhisk-devtools#102]
The Maven Java example, as shown in the README, does not work:

```
wsk -i action create md5hasher target/maven-java.jar --main org.apache.openwhisk.example.maven.App
error: Unable to create action 'md5hasher': The requested resource does not exist. (code 1470)
```

**Comment by kameshsampath** [comment]
@galderz  - can you run the command with `-v` option and tell post the output ?

**Comment by galderz** [comment]
It's [here](https://gist.github.com/galderz/a3b5f1d419d7601dc7c991f1d99f0b60). Note the class name is different since I"m running this in a different project. But the issue appears no matter what the class name passed in.

**Comment by kameshsampath** [comment]
I just now tried to create a action form the example :
```➜  maven-java wsk action create mvnjava target/maven-java.jar --main org.apache.openwhisk.example.maven.App
ok: created action mvnjava
➜  maven-java wsk action invoke mvnjava -p text test --result
{
    "md5": "098f6bcd4621d373cade4e832627b4f6",
    "text": "test"
}
```
I feel there should be something not rightly configured/deployed in you setup. 

What does your `wsk property get ` look like ? We can also take a dig at it when have our call tomorrow

**Comment by ddragosd** [comment]
@galderz is this still an issue or can we close it otherwise ?

**Comment by kameshsampath** [comment]
We can close it I have fixed it for @galderz it was more of setup and config of OW
