### ISSUE TITLE
Build for docker-compose fails

### ISSUE THREAD

**Issue by moritzraho** [apache/incubator-openwhisk-devtools#106]
steps: Cloned repo then `cd docker-compose` then `make quick-start`

error same as in: https://travis-ci.org/apache/incubator-openwhisk-devtools/jobs/358731448

probably related to: https://github.com/apache/incubator-openwhisk/commit/e2c1004c2ea36b217d39663f6a3cc2941caa0008

solved locally by replacing  `ddragosd/ansible:2.3.1.0-debian8` in `docker-compose/Makefile` at line 204  with `ddragosd/ansible:2.4.0.0-debian8`

**Comment by jthomas** [comment]
@moritzraho Thanks for noticing this and finding the probable issue. Would you be able to open the PR to make this change?

**Comment by moritzraho** [comment]
Done :)

**Comment by lornajane** [comment]
Thanks!  I ran into this exact thing today and it was so satisfying to be able to just pull the change :)
