### ISSUE TITLE
make quick-start fails when DOCKER_HOST isn't set

### ISSUE THREAD

**Issue by lornajane** [apache/incubator-openwhisk-devtools#108]
When I run `make quick-start`, the task just hangs.  I ran each task individually and the problem is that the `DOCKER_HOST_IP` (set on line 14) is empty.  This is because newish docker ships with the HTTP API disabled, so I have my `DOCKER_HOST` empty otherwise all my docker commands fail.

I'm not sure what the "right" way of getting the IP address for machines configured this way would be (I'm on Ubuntu 17.10), for example I can ask my computer what it thinks its IP is but I believe the second entry here is the right one:

```
$ hostname -I
10.1.0.121 172.17.0.1 172.18.0.1 
```

A script like this works perfectly, but I am not sure if it's "safe" or what the right thing to do is on other platforms.
```
$ hostname -I|cut -f2 -d ' '
172.17.0.1
```

**Comment by neerava** [comment]
Looks similar to https://github.com/apache/incubator-openwhisk-devtools/issues/109#issuecomment-378214868
Please check and try adding ifconfig in your path.

**Comment by ddragosd** [comment]
Now that https://github.com/apache/incubator-openwhisk-devtools/pull/110 is merged, can you retry ?

**Comment by compiaffe** [comment]
I am running into the same issue. Setting the DOCKER_HOST_IP to my ip address, but not 127.0.0.1 solves the issue.

My setup is slightly different as I have intentionally not added docker to the sudoers group. Due to that I have to execute every docker command with `sudo` - `sudo docker-compose`.

**Comment by lornajane** [comment]
Finally got time to retry with my linux machine and I had a similar but different problem.  I now need to set `export DOCKER_HOST_IP=172.17.0.1` which refers to the host machine and works from both the host machine itself and from inside the containers.  I believe this value is automatically set on OS X, but it wasn't for me (now on Ubuntu 18.04).

**Comment by satwikk** [comment]
As this issue is not closed yet, thus mentioning another "**command not found**" type issue. 
In a clean installation (in my case Ubuntu 14.04) - '_docker-compose_' command in not present on the machine. Neither does it ship with default 'docker-ce' installation. 

Change Suggestion - the 'Makefile' must do the following,

1. check for 'docker-compose' on the system, 
         - `docker-compose --version`
2. if not found then install 
         - ``sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose``

Or at least include this in the [Quick Start](https://github.com/apache/incubator-openwhisk#quick-start) installation with Docker.

**Comment by ddragosd** [comment]
@satwikk `docker-compose` is listed as a prereq in https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/README.md#prerequisites

Installing `docker-compose` automatically may put a burden to maintain such installer for multiple platforms.

**Comment by ddragosd** [comment]
@lornajane is the `DOCKER_HOST_IP` issue still present ?

**Comment by etagwerker** [comment]
I'm still running into this issue. I'm not sure if this is the same issue. I've tried setting DOCKER_HOST_IP to 127.0.0.1 and 172.17.0.1

It continues to get stuck here: 

```
waiting for the Whisk controller to come up ...
until $(curl --output /dev/null --silent --head --fail http://172.17.0.1:8888/ping); do printf '.'; sleep 5; done
............................
```

You can see the verbose log over here: https://gist.github.com/etagwerker/47387ef65f52fbac744d4012882d7404

I'm using a Linux Amazon AMI and this version of docker-compose: 

```
$ docker-compose --version
docker-compose version 1.22.0, build f46880fe
[ec2-user@ip-10-0-0-55 docker-compose]$ uname -a
Linux ip-10-0-0-55 4.14.72-68.55.amzn1.x86_64 #1 SMP Fri Sep 28 21:14:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rabbah** [comment]
Closing as fixed.
