### ISSUE TITLE
"Make run" doesn't work correctly

### ISSUE THREAD

**Issue by kuntsevichalex** [apache/incubator-openwhisk-devtools#122]
If I run `make stop` and then `make run`, it seems to be up again, but then once I try to create and invoke an action I get the following message:
`error: Unable to invoke action 'test': The connection failed, or timed out. (HTTP status code 500)`

**Comment by rabbah** [comment]
I could not reproduce this. It's possible - based on the status code - that either the api gw didn't come up cleanly on make run. Without more details, I think this isn't actionable. If it's still an issue, please reopen and post all the logs from make run.
