### ISSUE TITLE
create sample action fail?

### ISSUE THREAD

**Issue by qiuhui** [apache/incubator-openwhisk-devtools#133]
when I try to create action using follwing cmd:
`wsk action create hello hello.js`
it failed! the output is:
error: Unable to create action 'hello': Put https://10.8.228.15/api/v1/namespaces/guest/actions/hello?overwrite=false: x509: cannot validate certificate for 10.8.228.15 because it doesn't contain any IP SANs
Run 'wsk --help' for usage.

**Comment by rabbah** [comment]
Use: wsk -i ...

**Comment by qiuhui** [comment]
@rabbah it works,Thanks!
