### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by zak93kost** [apache/incubator-openwhisk-devtools#143]
I am trying to build openwhisk on windows but all of my tries end up with no solution. Is it possible for anyone to let us know the steps of building it on windows? I have troubles with the make comand and when I am using the ubuntu for windows terminal I have a problem with docker pull.

**Comment by chetanmeh** [comment]
Most likely build would not work on Windows. Instead of direct build it may be better to use the [Vagrant way][1] as there most work happen within the ubuntu vm

[1]: https://github.com/apache/incubator-openwhisk/tree/master/tools/vagrant

**Comment by chetanmeh** [comment]
This is tracked in #119. So resolving this as closed
