### ISSUE TITLE
Add more consistency to the Docker Compose `make` command line interface

### ISSUE THREAD

**Issue by Juice10** [apache/incubator-openwhisk-devtools#149]
The docker compose make commands are lacking some consistency. 
We currently have `make stop` and `make restart` but no `make start`. We do however have a `make run` and a `make quick-start`. I suggest we alias one of these two to `make start`.

We have more inconsistency in the use of `-`'s and `_`'s. Examples:
```
quick-start
add-catalog
download-catalog
quick-start-pause
quick-start-info
docker_build
docker_pull
docker_pull_full
download-cli
```

I suggest we rename the ones that use underscore (`_`) to dash (`-`) since most of the commands use dash and only a few of them use underscores. For backwards compatibility's sake we should keep the old ones but add a depreciation warning.

Let me know what you think of these suggestions. I'm not the expert here, just trying to make things more consistent and intuitive so that new users have an easier time using the tools.

**Comment by ddragosd** [comment]
@Juice10 👍 . If you wanna work on a PR we can get it merged.

**Comment by Juice10** [comment]
@ddragosd created a pull request for it here: 
https://github.com/apache/incubator-openwhisk-devtools/pull/154

**Comment by ddragosd** [comment]
thanks a lot @Juice10 . The PR has been merged and I'm closing this issue.
