### ISSUE TITLE
docker skeleton does not install correctly

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-devtools#157]
After deploying with compose, try

```
> wsk -i sdk install docker
error: The docker SDK installation failed: Error unGzipping file 'blackbox.tar.gz': Unable to unzip file 'blackbox.tar.gz': gzip: invalid header
```

Is the skeleton packed into the router image?

**Comment by ddragosd** [comment]
good catch @rabbah. I didn't test the `sdk install`. Is it supposed to download something via the gateway ?

**Comment by rabbah** [comment]
right... the nginx upstream provides a link to the tar ball released here https://github.com/apache/incubator-openwhisk-runtime-docker/releases, see https://github.com/apache/incubator-openwhisk/blob/05f916c746e6ca2860d50952086a37b6bdab239c/ansible/roles/nginx/templates/nginx.conf.j2#L116

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/blob/05f916c746e6ca2860d50952086a37b6bdab239c/ansible/roles/nginx/templates/nginx.conf.j2#L116
