### ISSUE TITLE
runc fails after deploying with compose

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-devtools#158]
After deploying with compose off master and running an action, the pause command fails and the container expunged. Is `runc` supported with compose?

<img width="1359" alt="screen shot 2018-09-06 at 12 18 54 pm" src="https://user-images.githubusercontent.com/4959922/45171173-b05c8480-b1cf-11e8-98a5-c9760674f393.png">

**Comment by ddragosd** [comment]
I'm referencing 2 previous conversations on this topic:
- https://github.com/apache/incubator-openwhisk/pull/2793
- https://github.com/apache/incubator-openwhisk/issues/2788

**Comment by alvarolopez** [comment]
I have the same issue. Is there any quick workaround that we can apply?

**Comment by rabbah** [comment]
This appears to be fixed now. 

`[2018-12-22T13:58:09.929Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess] running /usr/bin/docker pause d9bc4b46027aeb2956672807848916c6b1626137195e5ca5b0294ad9fea62be8 (timeout: 10 seconds) [marker:invoker_docker.pause_start:820248]
`
