### ISSUE TITLE
Run OpenWhisk in Mesos

### ISSUE THREAD

**Issue by ddragosd** [apache/incubator-openwhisk-devtools#17]
Create DCOS packages to deploy the OpenWhisk components. 
This issue depends on https://github.com/openwhisk/openwhisk/pull/2081

**Comment by csantanapr** [comment]
@ddragosd now the images are being built and pushed to dockerhub https://hub.docker.com/u/openwhisk/ including a couchdb-snapshot

**Comment by ddragosd** [comment]
@csantanapr 💯 ! Will give it a try these days, as soon as I get a chance.

**Comment by duynguyen** [comment]
PR opened [openwhisk/openwhisk-devtools#20](https://github.com/openwhisk/openwhisk-devtools/pull/20).

**Comment by ddragosd** [comment]
The work for deploying on Mesos is moved into https://github.com/apache/incubator-openwhisk-deploy-mesos repo.
