### ISSUE TITLE
failing with "dial tcp: lookup minio.docker on 127.0.0.11:53: no such host"

### ISSUE THREAD

**Issue by karun19** [apache/incubator-openwhisk-devtools#173]
Always fails at this point. I am new to it, please help.

Downloading source tar ball master....
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    104      0 --:--:--  0:00:01 --:--:--   104
100 10.4M  100 10.4M    0     0   357k      0  0:00:29  0:00:29 --:--:--  294k
Unpacking tarball.
downloading the CLI tool ... 
downloading cli for linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626    0   626    0     0    478      0 --:--:--  0:00:01 --:--:--   478
100 3391k  100 3391k    0     0   315k      0  0:00:10  0:00:10 --:--:--  487k
pulling the docker images short list... 
Using default tag: latest
latest: Pulling from openwhisk/controller
Digest: sha256:aa2498cb3c7b7ae08271019c88f7832b4daf28b1da72fe96d8f6cd59e594eba5
Status: Image is up to date for openwhisk/controller:latest
Using default tag: latest
latest: Pulling from openwhisk/invoker
Digest: sha256:b5e1c96450df2d3bb4645bf322bcf84041b0d65d93746818a9314e5e6b939118
Status: Image is up to date for openwhisk/invoker:latest
Using default tag: latest
latest: Pulling from openwhisk/nodejs6action
Digest: sha256:c4afd017e382ba52e789fb63a8801998a758745e22746afcdbcb7441d85acf04
Status: Image is up to date for openwhisk/nodejs6action:latest
Using default tag: latest
latest: Pulling from openwhisk/dockerskeleton
Digest: sha256:833a76ab0e61b6ff32cff8baee0cab18791ce49f0e66d03e3303eb4abbe95951
Status: Image is up to date for openwhisk/dockerskeleton:latest
host ip address: 10.0.2.15
checking required ports ... 
 ... OK
  ... preparing api-gateway configuration
pinging minio...
.Creating network "openwhisk_default" with the default driver
Pulling minio (minio/minio:RELEASE.2018-07-13T00-09-07Z)...
Creating openwhisk_minio_1_1c9d6f246d33 ... done
 ... OK
Unable to find image 'openwhisk/apigateway:latest' locally
latest: Pulling from openwhisk/apigateway
4fe2ade4980c: Already exists 
19f5156bba76: Pull complete 
f896f91d72d0: Pull complete 
301746a9771e: Pull complete 
8db5b9e441b9: Pull complete 
b716bb09fe55: Pull complete 
7f60dc362c8c: Pull complete 
5d90600c1954: Pull complete 
c275bf414e8a: Pull complete 
943f4a5dd4d8: Pull complete 
51d717412fa1: Pull complete 
334b7f89b58e: Pull complete 
Digest: sha256:f3b0e93a844964f11cb9160f84b4c3266648c82cc6234ebba4c2a1d72b3dbef9
Status: Downloaded newer image for openwhisk/apigateway:latest
2018/11/01 07:21:08 ERROR : Attempt 1/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/01 07:21:58 ERROR : Attempt 2/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/01 07:22:43 ERROR : Attempt 3/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/01 07:22:43 Failed to mkdir: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
Makefile:202: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by bipinm** [comment]
Same issue, unable to resolve even after setting "export DOCKER_HOST_IP=172.17.0.1". Did you solve this already ?

```
checking required ports ... 
 ... OK
  ... preparing api-gateway configuration
pinging minio...
Creating openwhisk_minio_1_1e6e41817cb1 ... done
 ... OK
2018/11/21 07:39:13 ERROR : Attempt 1/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/21 07:39:59 ERROR : Attempt 2/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/21 07:40:39 ERROR : Attempt 3/3 failed with 1 errors and: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
2018/11/21 07:40:39 Failed to mkdir: RequestError: send request failed
caused by: Head http://minio.docker:9000/api-gateway: dial tcp: lookup minio.docker on 127.0.0.11:53: no such host
Makefile:204: recipe for target 'setup' failed
make: *** [setup] Error 1
```

**Comment by Juice10** [comment]
@karun19 @bipinm I just submitted a fix for this. Could you both pull in the new update and see if this issue still persists?

**Comment by rabbah** [comment]
@Juice10 I just tried devtools off master and had no issues deploying correctly. Will close speculatively as fixed.
