### ISSUE TITLE
error: Authenticated user does not have namespace 'guest' during make quick-start

### ISSUE THREAD

**Issue by ste23droid** [apache/incubator-openwhisk-devtools#187]
Hi there,
on this setup:
- MacBook Pro (Retina, 13-inch, Early 2015), 8 GB of RAM, 10.14.1 (18B75) Mojave
- Docker Desktop Version 2.0.0.0-mac81 (29211), Stable Channel

`make quick-start` script fails almost any time with the error:
```
error: Authenticated user does not have namespace 'guest'; set command failed: The connection failed, or timed out. (HTTP status code 500)
make: *** [init-whisk-cli] Error 1
```
This is very frustrating indeed, is there any workaround/tip to solve it?
Have a nice day!

**Comment by rabbah** [comment]
@ste23droid at which point does this fail? I just tried to replicate and `make quick-start` runs cleanly.
Inspecting the controller afterward:

```
> wsk -i --apihost http://localhost:8888 namespace list
namespaces
guest
```

Can you check your make logs for earlier errors?

**Comment by ste23droid** [comment]
Hi @rabbah,
It happens in the very end with both `make run` and  `make quick-start`, when the script tries to start the hello world function example. I think the error is generated there. Lately I've discovered that the error appears, but actually openwhisk is started fine and the guest namespace is created (confirmed by your answer also). Still the error should not be shown, very misleading.

Have a nice day!

**Comment by axelrose** [comment]
same problem here

I have to clean `~/tmp/openwhisk` directory, make destroy and start over.

The namespace 'guest' on http://localhost:8888 is available. No obvious preceding error. I'd be glad to help on finding root cause and fixing this.
