### ISSUE TITLE
Update readmes to be clear what's the state of the kubernetes support

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-devtools#19]
Update main readme with a section on kubernetes stating that it's work in progress not ready yet. 
Update the readme under kubernetes stating what's currently working. For example only the couchdb container is being deploy. As we make progress and get more things working we can update the readme. 

I had false impression that I could deploy the controller, Kafka and invoker.

**Comment by DanLavine** [comment]
I will submit a PR to the main READMe with some info about the Kubernetes README once this [pr](https://github.com/apache/incubator-openwhisk-devtools/pull/31) is merged. I have the `(work in progress)` info at the top of the README which is still there. Couple of cleanup things to go through once everything is merged, but you are able to successfully deploy OpenWhisk on Kube.

**Comment by DanLavine** [comment]
@csantanapr This issue can be closed since we have moved all of the Kube stuff to its own Repo.

**Comment by mrutkows** [comment]
Closed issue as much has changed in regard to docs since April 5th (and of course its no longer in this repo.)
