### ISSUE TITLE
"waiting for the Whisk controller to come up ..." forever

### ISSUE THREAD

**Issue by aBetterFun** [apache/incubator-openwhisk-devtools#219]
downloaded the latest version, still got this result.

**Comment by rabbah** [comment]
When this happens, it's like the controller crashed - there is a PR #155 to fix the forever part that you could try from @Juice10.

Can you check the controller logs in your tmp folder and post any errors that are logged there?

**Comment by aBetterFun** [comment]
tried adding "wait-for-docker-compose-up" manually, yet got some bugs:

/bin/sh: 5: function: not found
/bin/sh: 7: Syntax error: ";" unexpected
Makefile:266: recipe for target 'wait-for-docker-compose-up' failed

could you please commit the verified changes?

**Comment by Juice10** [comment]
I just pushed a fix, feel free to merge, should work now.

**Comment by rabbah** [comment]
#155 now merged. @aBetterFun can you see if that helps?

**Comment by aBetterFun** [comment]
Thank you so much, it finally works. And the reason it didn't work is probably not the script itself. Here is what I did. I created an EC2 server with only one vCPU. And I "make quick-start" with default configuration. 
I checked the log and found the limitation of CPU might cause the problem. So I created another one with multiple vCPUs, also pulled the latest version, and it worked.
Thank you again, I have been stuck for days.

**Comment by rabbah** [comment]
Glad you’re unstuck. Sorry it took a bit of time.

**Comment by aleks-myplanet** [comment]
Hi,
I'm getting this exact same issue since Mon Dec 9th 2019 (may have started sooner but was fine on Fri Dec 6th 2019).
Was there any updates to the docker images that perhaps broken it once again?

**Comment by arcsud91** [comment]
Hi, even I am facing the same since 9th Dec Morning. I believe some changes in the image has triggered this behavior.

**Comment by VaguelySerious** [comment]
Hi, I'm also facing the same issue and haven't been able to find a workaround. My system:
Linux: 5.4.2-1
Distro: Manjaro KDE
OpenWhisk Devtools: git master
Python: 3.8
OpenJDK: 13
Docker: 19.03.5-ce
docker-compose: 1.24.1

I had to wipe my drive and set it all up again two weeks ago, after which I couldn't get OpenWhisk to run anymore.

**Comment by style95** [comment]
@VaguelySerious 
Could you share the controller logs?
Generally, it would be located under `~/tmp/openwhisk/controller/logs/`

**Comment by VaguelySerious** [comment]
Haven't changed my system since 5 days ago (maybe a restart or two), but `make quick-start` now produces a different error after trying to execute the `hello` function.
Still not sure what caused the original "waiting or the Whisk controller to come up" but I haven't been able to reproduce it. So while still stuck, this is probably off topic now and I'll search for solution elsewhere, but for documentation purposes here's the logs for this error:
[openwhisk_log.txt](https://github.com/apache/openwhisk-devtools/files/3997795/openwhisk_log.txt)

**Comment by style95** [comment]
@VaguelySerious ok.
So are you still facing the issue or not?
Would it be ok to keep this issue closed?

**Comment by VaguelySerious** [comment]
@style95 I'm not facing this issue anymore. You can keep it closed.
