### ISSUE TITLE
Unable to invoke action 'hello'

### ISSUE THREAD

**Issue by ffissore** [apache/incubator-openwhisk-devtools#246]
`make quick-start` ends with an error. Errors vary, but this is what I consistently get now that I've downloaded all docker images

```
error: Unable to invoke action 'hello': The server is currently unavailable (because it is overloaded or down for maintenance). (code 8BvMAenAakNUkY3R8HLODN9BHb5qcaZy)
```

near the end of the output, and at its end

```
[2019-04-12T12:55:11.070Z] [ERROR] [#tid_sid_unknown] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for health-0: 30006 ms has passed since batch creation plus linger time
tail: impossibile aprire '/home/federico/tmp/openwhisk/controller/logs/controller-local_logs.log' per la lettura: File o directory non esistente
Makefile:381: set di istruzioni per l'obiettivo "hello-world" non riuscito
```

which is the italian for "file not found" and indeed `controller-local_logs.log` does not exists

Complete output available here https://gist.github.com/ffissore/d10f2b950f1afc9a71e73033eb898d67

I'm on Ubuntu 16.04.6 LTS, docker 18.09.4, docker-compose 1.24.0

**Comment by rabbah** [comment]
There was a bug in the log file location, and this issue may be addressed by https://github.com/apache/incubator-openwhisk-devtools/commit/45918110276d9c8f7d0089e45f5dfcbb4f1a291c.
