### ISSUE TITLE
ERROR: for apigateway '"/bin/sh" 28: let: not found' repeatedly cycles

### ISSUE THREAD

**Issue by VestigeJ** [apache/incubator-openwhisk-devtools#250]
`<pre><font color="#D3D7CF">$ </font>make quick-start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    395      0 --:--:-- --:--:-- --:--:--   395
100 14.6M    0 14.6M    0     0  7511k      0 --:--:--  0:00:01 --:--:-- 10.9M
Unpacking tarball.
downloading the CLI tool ... 
downloading cli for linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626    0   626    0     0   1914      0 --:--:-- --:--:-- --:--:--  1914
100 3852k  100 3852k    0     0  2578k      0  0:00:01  0:00:01 --:--:-- 4064k
Using default tag: latest
latest: Pulling from openwhisk/controller
Digest: sha256:b1858c8369bf81adeb4687f9cd4831df07aa988b7216e189fbeb710a8b76987f
Status: Image is up to date for openwhisk/controller:latest
Using default tag: latest
latest: Pulling from openwhisk/nodejs6action
Digest: sha256:ee0ad34744a2994cc961e6b159e6b94bb61164bea0f32cbf92ed953afa14b1db
Status: Image is up to date for openwhisk/nodejs6action:latest
Using default tag: latest
latest: Pulling from openwhisk/dockerskeleton
Digest: sha256:7423b688fa85f7b315423e1a75b3cdac7c24e9ece64eb8dd55709bde59ff9c94
Status: Image is up to date for openwhisk/dockerskeleton:latest
pulling the docker images short list... 
Using default tag: latest
latest: Pulling from openwhisk/invoker
Digest: sha256:349ad3448b0b4cecb4da223a2f0dc541d4b70698a9ed7583ca3e5d8e6198412f
Status: Image is up to date for openwhisk/invoker:latest
host ip address: 192.168.0.247
checking required ports ... 
 ... OK
cat: /home/machine/tmp/openwhisk/local.env: No such file or directory
cat: /home/machine/tmp/openwhisk/local.env: No such file or directory
cat: /home/machine/tmp/openwhisk/local.env: No such file or directory
cat: /home/machine/tmp/openwhisk/local.env: No such file or directory
cat: /home/machine/tmp/openwhisk/local.env: No such file or directory
  ... preparing api-gateway configuration
pinging minio...
.<font color="#C4A000">WARNING</font>: The DOCKER_COMPOSE_HOST variable is not set. Defaulting to a blank string.
Starting openwhisk_minio_1 ... <font color="#4E9A06">done</font>
 ... OK
<font color="#C4A000">WARNING</font>: The DOCKER_COMPOSE_HOST variable is not set. Defaulting to a blank string.
<font color="#C4A000">WARNING</font>: The DOCKER_COMPOSE_HOST variable is not set. Defaulting to a blank string.
generating server certificate request
generating self-signed password-less server certificate
Signature ok
subject=/C=US/ST=NY/L=Yorktown/O=OpenWhisk/CN=192.168.0.247
Getting Private key
generate keystore
Waiting till all containers are powered up... 
Removing openwhisk_apigateway_1
openwhisk_minio_1 is up-to-date
Creating openwhisk_db_1        ... <font color="#4E9A06">done</font>
Creating openwhisk_redis_1     ... <font color="#4E9A06">done</font>
Creating openwhisk_zookeeper_1 ... <font color="#4E9A06">done</font>
Creating openwhisk_kafka_1     ... <font color="#4E9A06">done</font>
Creating openwhisk_kafka-rest_1 ... <font color="#4E9A06">done</font>
Creating openwhisk_controller_1 ... 
Creating openwhisk_controller_1      ... <font color="#4E9A06">done</font>
Creating openwhisk_invoker_1                   ... <font color="#4E9A06">done</font>
/bin/sh: 28: let: not found
Recreating c19ddf139321_openwhisk_apigateway_1 ... 
Creating openwhisk_kafka-topics-ui_1           ... <font color="#4E9A06">done</font>
Recreating c19ddf139321_openwhisk_apigateway_1 ... <font color="#CC0000">error</font>

ERROR: for c19ddf139321_openwhisk_apigateway_1  Cannot start service apigateway: driver failed programming external connectivity on endpoint openwhisk_apigateway_1 (daece4aa82073c14fef77901b51a4c4ba913afa27a05be8ea073ff494701ca40): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for apigateway  Cannot start service apigateway: driver failed programming external connectivity on endpoint openwhisk_apigateway_1 (daece4aa82073c14fef77901b51a4c4ba913afa27a05be8ea073ff494701ca40): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
<font color="#CC0000">ERROR</font>: Encountered errors while bringing up the project.
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
^CMakefile:276: recipe for target &apos;wait-for-docker-compose-up&apos; failed
make: *** [wait-for-docker-compose-up] Interrupt

Stopping openwhisk_minio_1 ... 
Stopping openwhisk_minio_1 ... <font color="#4E9A06">done</font>
<font color="#D3D7CF">$ </font>
</pre>`

**Comment by VestigeJ** [comment]
This is the output from a fresh install of Docker-CE, running on Ubuntu 18.04 and following the Quickstart instructions. 
$ git clone https://github.com/apache/incubator-openwhisk-devtools.git
$ cd incubator-openwhisk-devtools/docker-compose
$ make quick-start

**Comment by ddragosd** [comment]
@VestigeJ it looks like the error in your case is that the port `80` is already in use somehow, maybe by another interface.  
``` Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use```
Can you double check ?

**Comment by VestigeJ** [comment]
Yep confirmed this is true - Apache running on Port 80. Although I'm curious now because I tried troubleshooting by setting up an LXD ubuntu instance that should be vanilla and encountered the same errors. 

I'm going to close this for now though because I've been thrown a different project for the time being.

**Comment by qriousgabriel** [comment]
I believe this is because the make is using /bin/sh instead of bash, and 'let' is a bash builtin. I've run into this problem, too. Have you managed to solve it?

**Comment by VestigeJ** [comment]
I have not attempted to yet - I got put on several other projects for the time being and haven’t been able to circle back.

**Comment by qriousgabriel** [comment]
Thanks for replying, actually I found a way to fix it, just add SHELL:=/bin/bash at the beginning of the Makefile and it will use bash. Hope this can be of help when you decided to come back to this.

**Comment by VestigeJ** [comment]
Brilliant! Thanks for posting the workaround. Would this be a potential feature request to check the environment for bash beforehand? My hope is to circle back but
I’m hunting for another job where I will get to work in this tech stack.

**Comment by autumnwindbleak** [comment]
Same problem happened here and found the solution: make bash link to shell. 
$ sudo ln -sf /bin/bash /bin/sh
