### ISSUE TITLE
quick-start fails to pull couchdb

### ISSUE THREAD

**Issue by dalelane** [apache/incubator-openwhisk-devtools#255]
I tried `make quick-start` for the first time, and it failed. 
The first error shown was
```
ERROR: manifest for apache/couchdb:2.1 not found
```

FWIW - I modified `services.db.image` in docker-compose.yml to use `apache/couchdb:2.3` and tried running `make quick-start` again and it worked okay then.

**Comment by rabbah** [comment]
thanks @dalelane - we should bump the image since that's what we use elsewhere.

**Comment by rabi82** [comment]
I tried @dalelane suggestion, but still not working 
stuck in: waiting for the database to come up ... on 111.11.111.11

**Comment by ddragosd** [comment]
@rabi82 what OS are you using ? Your problem might be different. In any case, feel free to retry with the fix merged by @rabbah .

**Comment by rabi82** [comment]
@rabbah , i am using cento os 7 ,  
the logs from couth DB :

[notice] 2019-05-07T19:04:51.404804Z nonode@nohost <0.360.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
[error] 2019-05-07T19:04:51.404932Z nonode@nohost emulator -------- Error in process <0.8062.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}

**Comment by Lei-Houjyu** [comment]
> I tried @dalelane suggestion, but still not working
> stuck in: waiting for the database to come up ... on 111.11.111.11

I met this problem, too. After I run `make quick-start`, I stuck at `waiting for the database to come up ... on 192.168.10.91`. Have you find any solution?
