### ISSUE TITLE
docker-compose make init-whisk-cli fails due to unknown --namespace flag

### ISSUE THREAD

**Issue by eggyal** [apache/incubator-openwhisk-devtools#260]
`make init-whisk-cli` in `docker-compose` fails upon invocation of `wsk property set` with `unknown flag: --namespace`.

https://github.com/apache/incubator-openwhisk-devtools/blob/1e4cf0e077e44b8f1d0a5debcd43e0b7a89aa024/docker-compose/Makefile#L344

Can this flag be safely removed?

**Comment by rabbah** [comment]
Yes you can drop it.

**Comment by rabbah** [comment]
If it works as expected with the change do you want to open a pull request?

**Comment by eggyal** [comment]
Thanks, it works—PR submitted.
