### ISSUE TITLE
quick-start failed with "open /my_mount/docker/tmp/GetImageBlob650075150: no such file or directory"

### ISSUE THREAD

**Issue by lyuxiaosu** [apache/incubator-openwhisk-devtools#268]
Hi openwhisk team, I run "sudo make quick-start" on my ubuntu-16.04 but failed with:
```Using default tag: latest
latest: Pulling from openwhisk/controller
4fe2ade4980c: Pulling fs layer
932858db6d53: Pulling fs layer
67726ed84b62: Pulling fs layer
596a1846c0b3: Waiting
1267a0e3b0e7: Waiting
b449773f48b0: Waiting
4557256edcb8: Waiting
97dfc2d86531: Waiting
9ed97f8375e8: Waiting
cee7adc53dc8: Waiting
d5a3b555f044: Waiting
90b4b952938b: Waiting
5842c21aea49: Waiting
487bfc0e1c55: Waiting
7e6083e9f1c3: Waiting
7765773bc7d4: Waiting
open /my_mount/docker/tmp/GetImageBlob650075150: no such file or directory
Makefile:114: recipe for target 'docker-pull-lean' failed
make: *** [docker-pull-lean] Error 1
```
I don't know how to fix it. Could you please see what is this problem? Thank you.

**Comment by rabbah** [comment]
are you able to run any `docker pull` commands?

**Comment by lyuxiaosu** [comment]
I think so because I have already deployed openwhisk based on kubernetes locally and it worked very fine. Before I tried docker compose, I had destroyed kubernetes cluster. I cannot reproduce this problem now because there is an another error right now caused by issue [269](https://github.com/apache/incubator-openwhisk-devtools/issues/269) . I will follow this issue when you fixed issue [269](https://github.com/apache/incubator-openwhisk-devtools/issues/269)

**Comment by lyuxiaosu** [comment]
Sorry, I just git pull and redid "sudo make quick-start", there showed some other errors, but this problem cannot be reproduced, I think you can close this issue, and I will open an other issue. Thank you.
