### ISSUE TITLE
controller fails to start due to consul 

### ISSUE THREAD

**Issue by masodu** [apache/incubator-openwhisk-devtools#45]
With latest dev tools code base controller fails to start 

- ~/tmp/openwhisk/controller/logs/controller-local_logs.log:
`[2017-07-17T11:10:38.767Z] [WARN] [??] [WhiskConfig] failed to read properties from consul: null
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at whisk.core.controller.Controller$.main(Controller.scala:181)
	at whisk.core.controller.Controller.main(Controller.scala)`

- ~/tmp/openwhisk/docker-compose.log: 
`consul_1       |     2017/07/17 11:54:34 [WARN] agent: http request failed 'http://172.18.0.8:8888/ping': Get http://172.18.0.8:8888/ping: dial tcp 172.18.0.8:8888: getsockopt: connection refused`

**Comment by ddragosd** [comment]
@masodu I think the error was coming from another source. Currently the build is failing due to other issues. I'll confirm once the build works well.

**Comment by ddragosd** [comment]
We're going to remove Consul from `docker-compose` now that it has been removed from the project. See https://github.com/apache/incubator-openwhisk/pull/2452 . I'm going to close this and open a separate PR for removing Consul.
