### ISSUE TITLE
travis build (and docker-compose based builds in general) fail with broken controller.env

### ISSUE THREAD

**Issue by gocallag** [apache/incubator-openwhisk-devtools#65]
The travis builds are failing as are local builds using the docker-compose method.  

Missing controller env variables

[2017-11-26T22:42:44.788Z] [INFO] [??] [Config] environment set value for db.provider
[2017-11-26T22:42:44.788Z] [INFO] [??] [Config] environment set value for db.password
[2017-11-26T22:42:44.789Z] [INFO] [??] [Config] environment set value for kafka.host
**[2017-11-26T22:42:44.789Z] [ERROR] [??] [Config] required property db.whisk.actions.ddoc still not set**
[2017-11-26T22:42:44.790Z] [ERROR] [??] [Controller] Bad configuration, cannot start.
[INFO] [11/26/2017 22:42:44.914] [Thread-0] [CoordinatedShutdown(akka://kamon)] Starting coordinated shutdown from JVM shutdown hook

and

[2017-11-26T23:10:41.380Z] [INFO] [??] [Config] environment set value for kafka.host
**[ERROR] [11/26/2017 23:10:41.352] [main] [Controller$(akka://controller-actor-system)] [??] [Config] required property controller.ha still not set**

and

**[2017-11-26T23:11:39.410Z] [ERROR] [??] [Config] required property db.whisk.activations.ddoc still not set**
[2017-11-26T23:11:39.411Z] [ERROR] [??] [Controller] Bad configuration, cannot start.

These are missing from docker-whisk-controller.env  -  I'm not sure what values they should have but as a test I added.

DB_WHISK_ACTIONS_DDOC=ddoc
DB_WHISK_ACTIVATIONS_DDOC=addoc
CONTROLLER_HA=false

The controller container now starts but ow in general does not work due to errors such as
ESC[36mdb_1          |ESC[0m [info] [<0.119.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.234.0>] Could not open file /usr/local/var/lib/couchdb/local_whisks.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.120.0>] 172.18.0.7 - - GET /local_whisks/whisk.system%2FinvokerHealthTestAction0 404
ESC[36mdb_1          |ESC[0m [error] [<0.237.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.120.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.241.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.118.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.245.0>] Could not open file /usr/local/var/lib/couchdb/local_whisks.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.117.0>] 172.18.0.7 - - GET /local_whisks/whisk.system%2FinvokerHealthTestAction0 404
ESC[36mdb_1          |ESC[0m [error] [<0.249.0>] Could not open file /usr/local/var/lib/couchdb/local_whisks.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [error] [<0.250.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.116.0>] 172.18.0.7 - - GET /local_whisks/whisk.system%2FinvokerHealthTestAction0 404
ESC[36mdb_1          |ESC[0m [info] [<0.117.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.255.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.116.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.261.0>] Could not open file /usr/local/var/lib/couchdb/local_whisks.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.209.0>] 172.18.0.7 - - GET /local_whisks/whisk.system%2FinvokerHealthTestAction0 404
ESC[36mdb_1          |ESC[0m [info] [<0.208.0>] 172.18.0.7 - - GET /local_whisks/whisk.system%2FinvokerHealthTestAction0 404
ESC[36mdb_1          |ESC[0m [error] [<0.264.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.208.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404
ESC[36mdb_1          |ESC[0m [error] [<0.267.0>] Could not open file /usr/local/var/lib/couchdb/local_activations.couch: no such file or directory
ESC[36mdb_1          |ESC[0m [info] [<0.209.0>] 172.18.0.7 - - POST /local_activations/_bulk_docs 404

**Comment by duynguyen** [comment]
I opened #64 to fix it. Can not merge yet as the build is failing (need #63 to get in first).

**Comment by ddragosd** [comment]
closing the issue as the PRs referenced above have been merged.
