### ISSUE TITLE
travis build (and docker-compose , make quick-start fails)

### ISSUE THREAD

**Issue by gocallag** [apache/incubator-openwhisk-devtools#66]
[root@HCC00317 incubator-openwhisk-devtools]# cd docker-compose/
[root@HCC00317 docker-compose]# make quick-start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3677  100  3677    0     0  24098      0 --:--:-- --:--:-- --:--:-- 24190
100   183  100   183    0     0    146      0  0:00:01  0:00:01 --:--:--   208
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0 10.6M    0     0  1910k      0 --:--:--  0:00:05 --:--:-- 3402k
building the CLI tool ...

FAILURE: Build failed with an exception.

* What went wrong:
Project 'tools' not found in root project 'openwhisk'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
make: *** [build-cli] Error 1

**Comment by ddragosd** [comment]
@gocallag this issue was fixed and I'm closing it.
