### ISSUE TITLE
Curl error when downloading source tar ball

### ISSUE THREAD

**Issue by mcdan** [apache/incubator-openwhisk-devtools#85]
```bash
make quick-start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to  port 80: Connection refused
100   183  100   183    0     0     81      0  0:00:02  0:00:02 --:--:--    90
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 10.8M  100 10.8M    0     0   839k      0  0:00:13  0:00:13 --:--:-- 2011k
downloading the CLI tool ...
downloading cli for mac
```
The download works would just be nice to understand what's happening here. Tracing the redirects by hand I don't even see a redirect to a non https server, so a bit confused.

**Comment by jonpspri** [comment]
Could you post the curl command you used to perform the download?  I'll try to reproduce.

**Comment by mcdan** [comment]
Pretty sure it's this line based on the log output:
https://github.com/apache/incubator-openwhisk-devtools/blob/92b19a565608d7534a7acac8b14849ff86cff198/docker-compose/Makefile#L43

**Comment by shazron** [comment]
I encountered this as well.

Could it be a Github anonymous request rate limit? `curl https://api.github.com/rate_limit`
https://developer.github.com/changes/2013-07-02-rate-limit-reset/ 

Although I don't believe I was using the GH API beforehand to reach the limit, unless there is some other process doing that (Docker?).

**Comment by mcdan** [comment]
I can change the URL to the public link the project has even when not signed in to see if that makes it happen.
https://github.com/apache/incubator-openwhisk/archive/master.tar.gz instead of the API one.

Not sure why if we hit a rate limit the request wouldn't just die.
