### ISSUE TITLE
Make run deleted old ~/.wskprops file

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk-devtools#86]
While running make run command the old ~/.wskprops file is deleted and a new one is created.
Wouldn't it be good to check if a file already exists or just overwrite and not delete it?

**Comment by jthomas** [comment]
This is a good suggestion. If the file exists, credentials could be written to a different file. The CLI can pick them up by setting the `WSK_CONFIG_FILE`. If you want to submit a PR for this, others can help you review and get it merged.

**Comment by rabbah** [comment]
Definitely should not delete the properties file!

**Comment by dzmitry-kankalovich** [comment]
As of now, I don't see it's deleting old file, but rather rewrites some properties there.

If I had set up custom `auth` key and `namespace`, then those would be overwritten back to `guest` user. 

IDK what's the proper way to handle the situation, maybe use `guest` for running checks and restoring previous credentials once it's done?

**Comment by rabbah** [comment]
Addressed in https://github.com/apache/incubator-openwhisk-devtools/pull/200.
The props file in ones home directory is not used or modified by `make quick-start`.

The deployment instead will create a local props file and print this at the end (or via `make quick-start-info`):
```
To invoke the function again use: make hello-world
To stop OpenWhisk use: make destroy
To use the wsk CLI: export WSK_CONFIG_FILE=/path/to/incubator-openwhisk-devtools/docker-compose/.wskprops
                    or copy the file to /your/home/.wskprops
```
