### ISSUE TITLE
[Feature] Create a "pull" target to let someone update their containers from upstream

### ISSUE THREAD

**Issue by mcdan** [apache/incubator-openwhisk-devtools#88]
Even when using :latest in a container tag, compose does not automatically pull new versions. You must use `docker-compose pull`. I propose adding a mirror `make pull` that will update the containers, this will not be part of the `make quick-start` to ensure we don't overwrite containers someone is working on locally.

Docker-compose issue stating how you must use pull:  https://github.com/docker/compose/issues/3574

**Comment by jthomas** [comment]
Great idea - I had this exact issue today where the images were out of date compared to the configuration files. Came here to raise the issue and found this...
